Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@xuanha401 
gshofficialgithubindonesia
/
autoreport-fb
12
1826
 Code
 Pull requests 0 Actions
 Projects 0
 Wiki
 Security 0
 Insights
autoreport-fb/autoreport-fb.rb /
 Angry React Only Update autoreport-fb.rb
41cd958 on 3 Sep, 2017
91 lines (76 sloc)  2.56 KB
  
require 'rubygems'
require 'mechanize'
require 'colorize'
require 'optparse'
require 'highline/import'

options = {}

puts ''
puts "#{'Quantum'.red} :: #{'Automata'.blue} => http://34.212.135.46/"
puts ''
puts "Created By {\n #{'Cinder'.red} :: #{'Automata'.blue} => https://www.facebook.com/cinderautomata \nThanks For Refrence: \n #{'Denny Darmawan'.green} => https://www.facebook.com/denny.darmawan.intra \n}"
puts "This Tools is who want to learn about Lib Mechanize. #{'Author'.red} May Not #{'Warranty'.red}"
puts ''

class Facebook < Mechanize
	user_agent_alias = 'Windows Mozilla'
	follow_meta_refresh = true

	def login(email, pass)
		get 'https://www.facebook.com/Rhymastic.Offical'
		form_login = page.form_with(:method => 'POST') do |a|
			a.email = checked2017@yahooo.com
			a.pass = hacutehihi901@9
		end.submit(form_login)
		pp form_login
	end

	def report_someone(ent)
		get "https://m.facebook.com/nfx/basic/question/?context_str={%22initial_action_name%22%3A%22RESOLVE_PROBLEM%22%2C%22breadcrumbs%22%3A[]%2C%22story_location%22%3A%22profile_someone_else%22%2C%22is_from_feed_tombstone%22%3Afalse%2C%22actions_taken%22%3A%22%22%2C%22is_rapid_reporting%22%3Afalse%2C%22reportable_ent_token%22%3A%22#{ent}%22%2C%22is_impostor%22%3A%22%22}&redirect_uri=%2Fprofile.php%3Fid%3D#{ent}" do |a|
			b = page.forms.first do |a|
				a['a'] = 'b'
			end
			c = b.radiobutton_with(:value => /account/).check
			d = a.form_with(:method => 'POST') do |a|
				puts 'Segment Report 1 Submitted'
			end.submit(d)
		end
		e = page.forms.first do |a|
			a['a'] = 'b'
		end
		f = e.radiobutton_with(:value => /fake/).check
		g = page.form_with(:method => 'POST') do |a|
			puts 'Segment Report 2 Submitted'
		end.submit(g)
		h = page.forms.first do |a|
			a['a'] = 'b'
		end
		i = h.radiobutton_with(:value => /REPORT_CONTENT/).check
		j = page.form_with(:method => 'POST') do |a|
			puts 'Review To Facebook'
		end.submit(j)
	end
end

facebook = Facebook.new

parser = OptionParser.new do |opts|
	opts.banner = 'Usage: ruby autoreport-fb.rb [options]'

	opts.on('-l', '--login', 'Login Into Facebook') do |l|
		options[:login] = l
	end

	opts.on('-p', '--person', 'Report Account') do |p|
		options[:person] = p
	end

	opts.on('-h', '--help', 'Puts Options') do
		puts opts
		puts ''
		puts 'example : ruby autoreport-fb.rb --login --person "profile_id" #without tag'
		puts ''
		exit
	end

end

parser.parse!

if options[:login]
	usr = ask("17h04:  ") { |a| a.echo = true}
	pwd = ask("hacutehihi901@9:  ") { |a| a.echo = "*" }
	facebook.login(usr, pwd)
end

if options[:person]
	facebook.report_someone(ARGV[2])
end

#BUDI DILARANG COPY PASTE !!1111!!1
© 2020 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
